-- 서린컴퍼니 V52.1 안정화 통합 SQL
-- Supabase > SQL Editor > New query에서 이 파일 전체를 붙여넣고 Run 하세요.

create extension if not exists pgcrypto;

-- 1. 전체 소통방
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index if not exists idx_chat_messages_created_at on public.chat_messages(created_at);
alter table public.chat_messages enable row level security;
drop policy if exists chat_messages_read on public.chat_messages;
create policy chat_messages_read on public.chat_messages for select to authenticated using (true);
drop policy if exists chat_messages_insert on public.chat_messages;
create policy chat_messages_insert on public.chat_messages for insert to authenticated with check (sender_id=auth.uid());
grant select,insert on public.chat_messages to authenticated;
do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null; end $$;

-- 서린컴퍼니 V41 직원 선택형 메신저
-- Supabase SQL Editor에서 이 파일 전체를 1회 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.messenger_rooms (
  id uuid primary key default gen_random_uuid(),
  room_type text not null check (room_type in ('direct','group')),
  title text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messenger_room_members (
  room_id uuid not null references public.messenger_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.messenger_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.messenger_rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists idx_messenger_members_user on public.messenger_room_members(user_id,room_id);
create index if not exists idx_messenger_messages_room_time on public.messenger_messages(room_id,created_at desc);

create or replace function public.is_messenger_member(p_room_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.messenger_room_members
    where room_id=p_room_id and user_id=p_user_id
  );
$$;

revoke all on function public.is_messenger_member(uuid,uuid) from public;
grant execute on function public.is_messenger_member(uuid,uuid) to authenticated;

alter table public.messenger_rooms enable row level security;
alter table public.messenger_room_members enable row level security;
alter table public.messenger_messages enable row level security;

drop policy if exists messenger_rooms_select on public.messenger_rooms;
create policy messenger_rooms_select on public.messenger_rooms
for select to authenticated
using (public.is_messenger_member(id,auth.uid()));

drop policy if exists messenger_members_select on public.messenger_room_members;
create policy messenger_members_select on public.messenger_room_members
for select to authenticated
using (public.is_messenger_member(room_id,auth.uid()));

drop policy if exists messenger_messages_select on public.messenger_messages;
create policy messenger_messages_select on public.messenger_messages
for select to authenticated
using (public.is_messenger_member(room_id,auth.uid()));

drop policy if exists messenger_messages_insert on public.messenger_messages;
create policy messenger_messages_insert on public.messenger_messages
for insert to authenticated
with check (sender_id=auth.uid() and public.is_messenger_member(room_id,auth.uid()));

create or replace function public.messenger_create_room(
  p_room_type text,
  p_title text,
  p_member_ids uuid[]
)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  v_room uuid;
  v_other uuid;
begin
  if auth.uid() is null then raise exception '로그인이 필요합니다.'; end if;
  if p_room_type not in ('direct','group') then raise exception '잘못된 대화방 방식입니다.'; end if;

  if p_room_type='direct' then
    if coalesce(array_length(p_member_ids,1),0)<>1 then raise exception '1:1 대화는 직원 한 명을 선택해야 합니다.'; end if;
    v_other:=p_member_ids[1];
    if v_other=auth.uid() then raise exception '본인과의 대화방은 만들 수 없습니다.'; end if;

    select r.id into v_room
    from public.messenger_rooms r
    where r.room_type='direct'
      and public.is_messenger_member(r.id,auth.uid())
      and public.is_messenger_member(r.id,v_other)
      and (select count(*) from public.messenger_room_members m where m.room_id=r.id)=2
    limit 1;
    if v_room is not null then return v_room; end if;
  else
    if nullif(trim(p_title),'') is null then raise exception '그룹방 이름을 입력하세요.'; end if;
    if coalesce(array_length(p_member_ids,1),0)<1 then raise exception '참여할 직원을 선택하세요.'; end if;
  end if;

  insert into public.messenger_rooms(room_type,title,created_by)
  values(p_room_type,case when p_room_type='group' then trim(p_title) else null end,auth.uid())
  returning id into v_room;

  insert into public.messenger_room_members(room_id,user_id)
  values(v_room,auth.uid())
  on conflict do nothing;

  insert into public.messenger_room_members(room_id,user_id)
  select v_room,x
  from unnest(p_member_ids) x
  join public.profiles p on p.id=x and coalesce(p.is_active,true)
  where x<>auth.uid()
  on conflict do nothing;

  return v_room;
end;
$$;

grant execute on function public.messenger_create_room(text,text,uuid[]) to authenticated;

create or replace function public.messenger_my_rooms()
returns table(
  room_id uuid,
  room_type text,
  display_name text,
  member_count bigint,
  last_message text,
  last_message_at timestamptz,
  unread_count bigint
)
language sql
stable
security definer
set search_path=public
as $$
  select
    r.id,
    r.room_type,
    case
      when r.room_type='group' then r.title
      else coalesce((
        select p.name
        from public.messenger_room_members m2
        join public.profiles p on p.id=m2.user_id
        where m2.room_id=r.id and m2.user_id<>auth.uid()
        limit 1
      ),'1:1 대화')
    end,
    (select count(*) from public.messenger_room_members mc where mc.room_id=r.id),
    (select mm.content from public.messenger_messages mm where mm.room_id=r.id order by mm.created_at desc limit 1),
    (select mm.created_at from public.messenger_messages mm where mm.room_id=r.id order by mm.created_at desc limit 1),
    (select count(*) from public.messenger_messages mm
      where mm.room_id=r.id and mm.sender_id<>auth.uid() and mm.created_at>coalesce(m.last_read_at,m.joined_at))
  from public.messenger_rooms r
  join public.messenger_room_members m on m.room_id=r.id and m.user_id=auth.uid()
  order by coalesce(
    (select max(mm.created_at) from public.messenger_messages mm where mm.room_id=r.id),
    r.created_at
  ) desc;
$$;

grant execute on function public.messenger_my_rooms() to authenticated;

create or replace function public.messenger_mark_read(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  update public.messenger_room_members
  set last_read_at=now()
  where room_id=p_room_id and user_id=auth.uid();
end;
$$;
grant execute on function public.messenger_mark_read(uuid) to authenticated;

create or replace function public.messenger_room_members(p_room_id uuid)
returns table(user_id uuid,name text,team text,"position" text,employee_no text)
language sql
stable
security definer
set search_path=public
as $$
  select p.id,p.name,p.team,p.position,p.emp_no
  from public.messenger_room_members m
  join public.profiles p on p.id=m.user_id
  where m.room_id=p_room_id
    and public.is_messenger_member(p_room_id,auth.uid())
  order by p.name;
$$;
grant execute on function public.messenger_room_members(uuid) to authenticated;

grant select on public.messenger_rooms to authenticated;
grant select on public.messenger_room_members to authenticated;
grant select,insert on public.messenger_messages to authenticated;

-- 실시간 메시지 수신
do $$
begin
  alter publication supabase_realtime add table public.messenger_messages;
exception when duplicate_object then null;
end $$;


-- 2. 최고관리자 표시 이름 보정
update public.profiles
set name='손동오', position='이사', is_super_admin=true
where upper(coalesce(emp_no,''))='EMP001';

-- 3. 비밀소통은 손동오 이사 수신용
-- 기존 private_messages 테이블을 유지하며, 송신자는 본인 내역만, 수신자는 본인 수신 내역만 조회합니다.
alter table if exists public.private_messages enable row level security;
drop policy if exists private_messages_read on public.private_messages;
create policy private_messages_read on public.private_messages
for select to authenticated
using (sender_id=auth.uid() or recipient_id=auth.uid() or public.is_super_admin());
drop policy if exists private_messages_insert on public.private_messages;
create policy private_messages_insert on public.private_messages
for insert to authenticated
with check (sender_id=auth.uid());
grant select,insert,update on public.private_messages to authenticated;

-- 4. 초기 차량 4대: 중복이면 기존 자료를 유지하고 이름만 보정
insert into public.fleet_vehicles (vehicle_name,vehicle_number,status) values
 ('모하비','22우8010','운행가능'),
 ('벤츠','215서1806','운행가능'),
 ('스포티지','174하9138','운행가능'),
 ('스타리아','807노5770','운행가능')
on conflict (vehicle_number) do update set vehicle_name=excluded.vehicle_name;

-- 완료
select 'V52.1 SQL 적용 완료' as result;
