-- 서린 물류 포털 V1 기본 데이터베이스
-- Supabase SQL Editor에서 전체 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  emp_no text unique not null,
  name text not null,
  department text,
  team text,
  position text,
  phone text,
  sort_order integer default 999,
  is_active boolean default true,
  is_super_admin boolean default false,
  can_receive_private boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.user_permissions (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  dashboard_view boolean default true,
  notices_view boolean default true,
  notices_manage boolean default false,
  organization_view boolean default true,
  community_view boolean default true,
  private_messages_use boolean default true,
  card_use boolean default true,
  card_manage boolean default false,
  card_export boolean default false,
  inventory_view boolean default true,
  inventory_manage boolean default false,
  inventory_export boolean default false,
  purchase_view boolean default true,
  purchase_approve boolean default false,
  kpi_view boolean default false,
  kpi_manage boolean default false,
  kpi_export boolean default false,
  employees_manage boolean default false,
  permissions_manage boolean default false,
  updated_at timestamptz default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id),
  recipient_id uuid not null references public.profiles(id),
  title text not null,
  content text not null,
  answer text,
  is_answered boolean default false,
  answered_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.corporate_card_expenses (
  id bigint generated by default as identity primary key,
  used_date date not null,
  card_owner text not null,
  actual_user text,
  account_category text,
  vendor text,
  item_description text,
  amount numeric(14,2) not null check (amount >= 0),
  receipt_status text default '미첨부' check (receipt_status in ('첨부','미첨부','해당없음')),
  receipt_url text,
  memo text,
  status text default '등록' check (status in ('등록','확인','반려','정산완료')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text,
  specification text,
  unit text,
  current_stock numeric(14,2) default 0,
  minimum_stock numeric(14,2) default 0,
  storage_location text,
  vendor text,
  unit_price numeric(14,2) default 0,
  barcode text,
  is_active boolean default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id),
  transaction_type text not null check (transaction_type in ('in','out','discard','adjust')),
  quantity numeric(14,2) not null check (quantity >= 0),
  person_name text,
  memo text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz default now()
);

create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id),
  item_name text not null,
  quantity numeric(14,2) default 1,
  estimated_amount numeric(14,2) default 0,
  reason text,
  status text default '대기' check (status in ('대기','승인','반려','구매완료')),
  approver_id uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  action text not null,
  table_name text,
  record_id text,
  details jsonb,
  created_at timestamptz default now()
);

-- 신규 Auth 사용자의 metadata를 profiles로 복사
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles(id, emp_no, name, department, team, position)
  values(
    new.id,
    upper(coalesce(new.raw_user_meta_data->>'emp_no', split_part(new.email,'@',1))),
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)),
    new.raw_user_meta_data->>'department',
    new.raw_user_meta_data->>'team',
    new.raw_user_meta_data->>'position'
  )
  on conflict (id) do nothing;

  insert into public.user_permissions(user_id) values(new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_super_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select is_super_admin from public.profiles where id=auth.uid()),false); $$;

create or replace function public.has_permission(permission_name text)
returns boolean language plpgsql stable security definer set search_path=public
as $$
declare result boolean;
begin
  if public.is_super_admin() then return true; end if;
  execute format('select coalesce(%I,false) from public.user_permissions where user_id=$1',permission_name)
  into result using auth.uid();
  return coalesce(result,false);
end;
$$;

alter table public.profiles enable row level security;
alter table public.user_permissions enable row level security;
alter table public.notices enable row level security;
alter table public.private_messages enable row level security;
alter table public.corporate_card_expenses enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.purchase_requests enable row level security;
alter table public.audit_logs enable row level security;

create policy "profiles readable by organization users" on public.profiles for select to authenticated using (public.has_permission('organization_view') or id=auth.uid());
create policy "profiles managed by admin" on public.profiles for all to authenticated using (public.has_permission('employees_manage')) with check (public.has_permission('employees_manage'));

create policy "own permission readable" on public.user_permissions for select to authenticated using (user_id=auth.uid() or public.has_permission('permissions_manage'));
create policy "permissions managed by admin" on public.user_permissions for all to authenticated using (public.has_permission('permissions_manage')) with check (public.has_permission('permissions_manage'));

create policy "notices readable" on public.notices for select to authenticated using (public.has_permission('notices_view'));
create policy "notices writable" on public.notices for all to authenticated using (public.has_permission('notices_manage')) with check (public.has_permission('notices_manage'));

create policy "private messages participant read" on public.private_messages for select to authenticated
using (sender_id=auth.uid() or recipient_id=auth.uid() or public.is_super_admin());
create policy "private messages sender insert" on public.private_messages for insert to authenticated
with check (sender_id=auth.uid() and public.has_permission('private_messages_use'));
create policy "private messages recipient update" on public.private_messages for update to authenticated
using (recipient_id=auth.uid() or public.is_super_admin()) with check (recipient_id=auth.uid() or public.is_super_admin());

create policy "card own or manager read" on public.corporate_card_expenses for select to authenticated
using (created_by=auth.uid() or public.has_permission('card_manage'));
create policy "card insert" on public.corporate_card_expenses for insert to authenticated
with check (created_by=auth.uid() and public.has_permission('card_use'));
create policy "card manager update" on public.corporate_card_expenses for update to authenticated
using (public.has_permission('card_manage')) with check (public.has_permission('card_manage'));
create policy "card manager delete" on public.corporate_card_expenses for delete to authenticated
using (public.has_permission('card_manage'));

create policy "inventory readable" on public.inventory_items for select to authenticated using (public.has_permission('inventory_view'));
create policy "inventory managed" on public.inventory_items for all to authenticated
using (public.has_permission('inventory_manage')) with check (public.has_permission('inventory_manage'));
create policy "inventory tx readable" on public.inventory_transactions for select to authenticated using (public.has_permission('inventory_view'));
create policy "inventory tx insert" on public.inventory_transactions for insert to authenticated
with check (created_by=auth.uid() and public.has_permission('inventory_manage'));

create policy "purchase own or approver read" on public.purchase_requests for select to authenticated
using (requester_id=auth.uid() or public.has_permission('purchase_approve'));
create policy "purchase request insert" on public.purchase_requests for insert to authenticated
with check (requester_id=auth.uid() and public.has_permission('purchase_view'));
create policy "purchase approver update" on public.purchase_requests for update to authenticated
using (public.has_permission('purchase_approve')) with check (public.has_permission('purchase_approve'));

create policy "audit admin read" on public.audit_logs for select to authenticated using (public.is_super_admin());
create policy "audit authenticated insert" on public.audit_logs for insert to authenticated with check (user_id=auth.uid());

-- 최초 관리자 생성 후 SQL Editor에서 본인 UUID로 아래를 1회 실행:
-- update public.profiles set is_super_admin=true, can_receive_private=true where emp_no='EMP001';
