begin;

create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  notification_type text not null default 'general',
  title text not null,
  body text not null default '',
  target_page text not null default 'dashboard',
  target_id text,
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_notifications_created_at
  on public.app_notifications(created_at desc);

alter table public.app_notifications enable row level security;

drop policy if exists app_notifications_authenticated_select on public.app_notifications;
create policy app_notifications_authenticated_select
on public.app_notifications for select to authenticated
using (true);

drop policy if exists app_notifications_authenticated_insert on public.app_notifications;
create policy app_notifications_authenticated_insert
on public.app_notifications for insert to authenticated
with check (true);

grant select,insert on public.app_notifications to authenticated;

create or replace function public.create_portal_notification_from_row()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  j jsonb:=to_jsonb(new);
  v_type text:=coalesce(tg_argv[0],'general');
  v_page text:=coalesce(tg_argv[1],'dashboard');
  v_title text;
  v_body text;
  v_target text;
  v_creator uuid;
begin
  v_target:=coalesce(j->>'id','');
  begin v_creator:=nullif(coalesce(j->>'created_by',j->>'requester_id',j->>'user_id'),'')::uuid;
  exception when others then v_creator:=null; end;

  if v_type='notice' then
    v_title:='새 공지 · '||coalesce(nullif(j->>'title',''),'공지사항');
    v_body:=left(coalesce(j->>'content','새 공지가 등록되었습니다.'),180);
  elsif v_type='purchase' then
    v_title:='새 물품구매 신청 · '||coalesce(nullif(j->>'item_name',''),nullif(j->>'product_name',''),'구매 요청');
    v_body:=coalesce(nullif(j->>'requester_name',''),'직원')||'님이 구매를 신청했습니다.';
  elsif v_type='dinner' then
    v_title:='새 회식방 · '||coalesce(nullif(j->>'title',''),'회식방');
    v_body:=coalesce(nullif(j->>'created_by_name',''),'직원')||'님이 회식방을 만들었습니다. 클릭해서 확인하세요.';
  elsif v_type='event' then
    v_title:='새 회사 일정 · '||coalesce(nullif(j->>'title',''),'일정');
    v_body:=coalesce(nullif(j->>'description',''),'새로운 회사 일정이 등록되었습니다.');
  else
    v_title:='서린컴퍼니 새 알림';
    v_body:='새로운 내용이 등록되었습니다.';
  end if;

  insert into public.app_notifications(notification_type,title,body,target_page,target_id,created_by)
  values(v_type,v_title,v_body,v_page,v_target,v_creator);
  return new;
end;
$$;

do $$
begin
  if to_regclass('public.notices') is not null then
    execute 'drop trigger if exists trg_notices_portal_notification on public.notices';
    execute 'create trigger trg_notices_portal_notification after insert on public.notices for each row execute function public.create_portal_notification_from_row(''notice'',''notices'')';
  end if;
  if to_regclass('public.purchase_requests') is not null then
    execute 'drop trigger if exists trg_purchase_portal_notification on public.purchase_requests';
    execute 'create trigger trg_purchase_portal_notification after insert on public.purchase_requests for each row execute function public.create_portal_notification_from_row(''purchase'',''purchase'')';
  end if;
  if to_regclass('public.dinner_rooms') is not null then
    execute 'drop trigger if exists trg_dinner_portal_notification on public.dinner_rooms';
    execute 'create trigger trg_dinner_portal_notification after insert on public.dinner_rooms for each row execute function public.create_portal_notification_from_row(''dinner'',''dinner'')';
  end if;
  if to_regclass('public.company_events') is not null then
    execute 'drop trigger if exists trg_events_portal_notification on public.company_events';
    execute 'create trigger trg_events_portal_notification after insert on public.company_events for each row execute function public.create_portal_notification_from_row(''event'',''events'')';
  end if;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.app_notifications;
exception when duplicate_object then null;
end $$;

notify pgrst,'reload schema';
commit;
