-- V126 운송비 관리 + 손동오 전용 통합보고서 + 연차 수정 안정화
begin;
create table if not exists public.freight_orders(
 id uuid primary key default gen_random_uuid(), ship_date date, arrival_date date, category text default '국내', customer text, address text, pallets numeric default 0, order_numbers text, notes text, status text default '등록', base_fare numeric default 0, waiting_fee numeric default 0, inspection_fee numeric default 0, loading_fee numeric default 0, stopover_fee numeric default 0, night_fee numeric default 0, other_fee numeric default 0, total_amount numeric default 0, ai_estimate numeric default 0, ai_basis text, created_by uuid references auth.users(id), created_by_name text, created_at timestamptz default now(), updated_at timestamptz default now()
);
alter table public.freight_orders enable row level security;
drop policy if exists "V126 freight select" on public.freight_orders;
create policy "V126 freight select" on public.freight_orders for select to authenticated using (
 public.is_super_admin() or public.has_permission('vehicles_view') or public.has_permission('vehicles_manage')
);
drop policy if exists "V126 freight insert" on public.freight_orders;
create policy "V126 freight insert" on public.freight_orders for insert to authenticated with check (
 auth.uid()=created_by and (public.is_super_admin() or public.has_permission('vehicles_view') or public.has_permission('vehicles_manage'))
);
drop policy if exists "V126 freight update" on public.freight_orders;
create policy "V126 freight update" on public.freight_orders for update to authenticated using (
 public.is_super_admin() or public.has_permission('vehicles_manage')
) with check (public.is_super_admin() or public.has_permission('vehicles_manage'));
drop policy if exists "V126 freight delete" on public.freight_orders;
create policy "V126 freight delete" on public.freight_orders for delete to authenticated using (public.is_super_admin());
-- Realtime
do $$ begin
 if not exists (
   select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='freight_orders'
 ) then alter publication supabase_realtime add table public.freight_orders; end if;
end $$;

-- 연차 직접수정 기능이 기존 배포본에서 누락된 경우를 보완합니다.
create table if not exists public.employee_leave_year_balances(
 employee_id uuid not null references public.profiles(id) on delete cascade,
 leave_year integer not null,
 base_annual_leave numeric default 0,
 annual_balance numeric default 0,
 comp_balance numeric default 0,
 updated_by uuid references auth.users(id),
 updated_at timestamptz default now(),
 primary key(employee_id,leave_year)
);
alter table public.employee_leave_year_balances enable row level security;
drop policy if exists "V126 leave year select" on public.employee_leave_year_balances;
create policy "V126 leave year select" on public.employee_leave_year_balances for select to authenticated using (
 employee_id=auth.uid() or public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage')
);
drop policy if exists "V126 leave year manage" on public.employee_leave_year_balances;
create policy "V126 leave year manage" on public.employee_leave_year_balances for all to authenticated using (
 public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage')
) with check (public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage'));

create table if not exists public.employee_leave_balance_history(
 id bigint generated by default as identity primary key,
 employee_id uuid not null references public.profiles(id) on delete cascade,
 leave_year integer not null,
 annual_before numeric default 0,
 annual_after numeric default 0,
 comp_before numeric default 0,
 comp_after numeric default 0,
 reason text,
 created_by uuid references auth.users(id),
 created_by_name text,
 created_at timestamptz default now()
);
alter table public.employee_leave_balance_history enable row level security;
drop policy if exists "V126 leave history select" on public.employee_leave_balance_history;
create policy "V126 leave history select" on public.employee_leave_balance_history for select to authenticated using (
 employee_id=auth.uid() or public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage')
);

create or replace function public.admin_set_employee_leave_year_balances(
 p_employee_id uuid,p_leave_year integer,p_annual_balance numeric,p_comp_balance numeric,p_reason text
) returns void language plpgsql security definer set search_path=public as $$
declare v_old public.employee_leave_year_balances%rowtype; v_name text; v_base numeric;
begin
 if not (public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage')) then raise exception '연차 수정 권한이 없습니다.'; end if;
 if p_annual_balance < 0 or p_comp_balance < 0 then raise exception '잔여일수는 0보다 작을 수 없습니다.'; end if;
 select * into v_old from public.employee_leave_year_balances where employee_id=p_employee_id and leave_year=p_leave_year for update;
 select coalesce(name,''),coalesce(annual_leave_granted,0) into v_name,v_base from public.profiles where id=p_employee_id;
 insert into public.employee_leave_year_balances(employee_id,leave_year,base_annual_leave,annual_balance,comp_balance,updated_by,updated_at)
 values(p_employee_id,p_leave_year,v_base,p_annual_balance,p_comp_balance,auth.uid(),now())
 on conflict(employee_id,leave_year) do update set annual_balance=excluded.annual_balance,comp_balance=excluded.comp_balance,updated_by=auth.uid(),updated_at=now();
 insert into public.employee_leave_balance_history(employee_id,leave_year,annual_before,annual_after,comp_before,comp_after,reason,created_by,created_by_name)
 values(p_employee_id,p_leave_year,coalesce(v_old.annual_balance,v_base),p_annual_balance,coalesce(v_old.comp_balance,0),p_comp_balance,p_reason,auth.uid(),coalesce((select name from public.profiles where id=auth.uid()),'관리자'));
end;$$;
grant execute on function public.admin_set_employee_leave_year_balances(uuid,integer,numeric,numeric,text) to authenticated;

create or replace function public.admin_initialize_employee_leave_year(
 p_employee_id uuid,p_leave_year integer,p_mode text,p_reason text
) returns void language plpgsql security definer set search_path=public as $$
declare v_base numeric;
begin
 if not (public.is_super_admin() or public.has_permission('employees_manage') or public.has_permission('calendar_manage')) then raise exception '연차 수정 권한이 없습니다.'; end if;
 select coalesce(annual_leave_granted,0) into v_base from public.profiles where id=p_employee_id;
 if p_mode='create' then
   insert into public.employee_leave_year_balances(employee_id,leave_year,base_annual_leave,annual_balance,comp_balance,updated_by,updated_at)
   values(p_employee_id,p_leave_year,v_base,v_base,0,auth.uid(),now()) on conflict(employee_id,leave_year) do nothing;
 elsif p_mode='reset' then
   insert into public.employee_leave_year_balances(employee_id,leave_year,base_annual_leave,annual_balance,comp_balance,updated_by,updated_at)
   values(p_employee_id,p_leave_year,v_base,0,0,auth.uid(),now()) on conflict(employee_id,leave_year) do update set base_annual_leave=excluded.base_annual_leave,annual_balance=0,comp_balance=0,updated_by=auth.uid(),updated_at=now();
 else raise exception '허용되지 않은 처리 방식입니다.'; end if;
end;$$;
grant execute on function public.admin_initialize_employee_leave_year(uuid,integer,text,text) to authenticated;

commit;
