-- 서린 ERP V64: 연도별 연차·대휴 장부 생성/초기화
-- Supabase SQL Editor에 전체 복사하여 한 번 실행하세요.

create table if not exists public.employee_leave_year_balances (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  leave_year integer not null check (leave_year between 2000 and 2100),
  base_annual_leave numeric(8,2) not null default 0,
  annual_balance numeric(8,2) not null default 0,
  comp_balance numeric(8,2) not null default 0,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now(),
  unique(employee_id, leave_year)
);

create table if not exists public.employee_leave_year_history (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  leave_year integer not null,
  action_type text not null,
  annual_balance numeric(8,2),
  comp_balance numeric(8,2),
  reason text,
  created_by uuid references public.profiles(id),
  created_by_name text,
  created_at timestamptz not null default now()
);

alter table public.employee_leave_year_balances enable row level security;
alter table public.employee_leave_year_history enable row level security;

drop policy if exists "leave year balances authenticated select" on public.employee_leave_year_balances;
create policy "leave year balances authenticated select"
on public.employee_leave_year_balances for select to authenticated using (true);

drop policy if exists "leave year history authenticated select" on public.employee_leave_year_history;
create policy "leave year history authenticated select"
on public.employee_leave_year_history for select to authenticated using (true);

create or replace function public.erp_can_manage_leave()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.profiles p
    left join public.user_permissions up on up.user_id=p.id
    where p.id=auth.uid()
      and (coalesce(p.is_super_admin,false) or coalesce(up.employees_manage,false) or coalesce(up.calendar_manage,false))
  );
$$;

create or replace function public.admin_initialize_employee_leave_year(
  p_employee_id uuid,
  p_leave_year integer,
  p_mode text default 'create',
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_base numeric(8,2);
  v_name text;
begin
  if auth.uid() is null or not public.erp_can_manage_leave() then
    raise exception '연차 관리 권한이 없습니다.';
  end if;
  if p_leave_year < 2000 or p_leave_year > 2100 then
    raise exception '기준연도를 확인하세요.';
  end if;
  select coalesce(annual_leave_granted,0) into v_base from public.profiles where id=p_employee_id;
  if not found then raise exception '직원 정보를 찾을 수 없습니다.'; end if;
  select name into v_name from public.profiles where id=auth.uid();

  insert into public.employee_leave_year_balances(
    employee_id,leave_year,base_annual_leave,annual_balance,comp_balance,created_by,updated_by
  ) values (
    p_employee_id,p_leave_year,v_base,v_base,0,auth.uid(),auth.uid()
  )
  on conflict(employee_id,leave_year) do update set
    base_annual_leave=excluded.base_annual_leave,
    annual_balance=case when p_mode='reset' then excluded.base_annual_leave else public.employee_leave_year_balances.annual_balance end,
    comp_balance=case when p_mode='reset' then 0 else public.employee_leave_year_balances.comp_balance end,
    updated_by=auth.uid(),updated_at=now();

  insert into public.employee_leave_year_history(employee_id,leave_year,action_type,annual_balance,comp_balance,reason,created_by,created_by_name)
  values(p_employee_id,p_leave_year,case when p_mode='reset' then 'reset' else 'create' end,v_base,0,p_reason,auth.uid(),v_name);

  return jsonb_build_object('success',true,'leave_year',p_leave_year,'base_annual_leave',v_base);
end;
$$;

create or replace function public.admin_set_employee_leave_year_balances(
  p_employee_id uuid,
  p_leave_year integer,
  p_annual_balance numeric,
  p_comp_balance numeric,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_base numeric(8,2);
  v_name text;
begin
  if auth.uid() is null or not public.erp_can_manage_leave() then
    raise exception '연차 관리 권한이 없습니다.';
  end if;
  if p_annual_balance < 0 or p_comp_balance < 0 then
    raise exception '잔여일수는 0보다 작을 수 없습니다.';
  end if;
  select coalesce(annual_leave_granted,0) into v_base from public.profiles where id=p_employee_id;
  if not found then raise exception '직원 정보를 찾을 수 없습니다.'; end if;
  select name into v_name from public.profiles where id=auth.uid();

  insert into public.employee_leave_year_balances(employee_id,leave_year,base_annual_leave,annual_balance,comp_balance,created_by,updated_by)
  values(p_employee_id,p_leave_year,v_base,p_annual_balance,p_comp_balance,auth.uid(),auth.uid())
  on conflict(employee_id,leave_year) do update set
    base_annual_leave=excluded.base_annual_leave,
    annual_balance=excluded.annual_balance,
    comp_balance=excluded.comp_balance,
    updated_by=auth.uid(),updated_at=now();

  insert into public.employee_leave_year_history(employee_id,leave_year,action_type,annual_balance,comp_balance,reason,created_by,created_by_name)
  values(p_employee_id,p_leave_year,'manual_set',p_annual_balance,p_comp_balance,p_reason,auth.uid(),v_name);

  return jsonb_build_object('success',true);
end;
$$;

grant execute on function public.erp_can_manage_leave() to authenticated;
grant execute on function public.admin_initialize_employee_leave_year(uuid,integer,text,text) to authenticated;
grant execute on function public.admin_set_employee_leave_year_balances(uuid,integer,numeric,numeric,text) to authenticated;

notify pgrst, 'reload schema';
